import { signIn } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { useEffect } from "react";

export default function Home() {
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === "authenticated") {
      void router.push("/adventures");
    }
  }, [status, router]);

  return (
    <>
      <Head>
        <title>AIVenture | Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[url('/login_background.jpeg')] bg-cover">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="rounded bg-white/20 p-3 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(26,93%,64%)]">AI</span>Venture
          </h1>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl font-bold text-white">Sign in with Google</p>

            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
              onClick={() => void signIn()}
            >
              Sign in
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
